language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm

before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - node console.log(process.env.googleApiKey)
  - npx jest --ci